# @adibenc
# FastAPI ms-hakkajiten single service
# docker compose -f docker-compose-single.yml up -d --build hakkajiten-tfm

services:
  hakkajiten-tfm:
    build:
      context: .
      dockerfile: Dockerfile-fastapi
    container_name: hakkajiten-tfm
    restart: always
    ports:
      - ${DOCKER_APP_HAKKA_PORT:-8002}:8000
    volumes:
      - .:/app
      - ./pyx/.jupyter/:/root/.jupyter/
      - ./.paddlex/:/root/.paddlex/
      # - jupyter_server_config.json:/root/.jupyter/jupyter_server_config.json
      - ${VOL_PY311_DIST}:/usr/local/lib/python3.11/dist-packages/
      - ${VOL_PY310_DIST}:/usr/local/lib/python3.10/dist-packages/
      - ${APP_DCK_SHARED_DIR:-./tmp}:/var/shared/
      - ${HAKKA_STORAGE_DIR:-./storage}:/app/storage/
      - ${HAKKA_STATIC_DIR:-./static}:/app/static/
    # command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000"
    command: bash -c "/app/setup.sh" # wip
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 5m30s
      timeout: 10s
      retries: 3
      start_period: 2m
    environment:
      - TZ=UTC
      - ENVIRONMENT=${ENVIRONMENT:-production}
      - DEBUG=${DEBUG:-false}
      - APP_URL=${APP_URL:-http://localhost:8002}
      - DB_HOST=${DB_HOST:-localhost}
      - DB_PORT=${DB_PORT:-5432}
      - DB_NAME=${DB_NAME:-hakkajiten}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASS=${DB_PASS:-postgres}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - MAIL_DRIVER=${MAIL_DRIVER:-terminal}
      - APPROOT=/app/
      - TEMPLATES_DIR=templates
      - STATIC_DIR=static
      - STORAGE_DIR=storage
      - APP_INIT_TYPE=${APP_INIT_TYPE}
      - VOL_PY311_DIST=${VOL_PY311_DIST}
      - VOL_PY310_DIST=${VOL_PY310_DIST}
    extra_hosts:
      - "l1:172.17.0.1"
      - "host.docker.internal:host-gateway"
    stdin_open: true
    tty: true
